### ISSUE TITLE
Can you release the code for training?

### ISSUE THREAD

**Issue by hszyq1234** [fabvio/Cascade-LD#1] opened 2019-07-16 06:44 UTC

**Comment by mengzhibin** [comment] 2019-07-28 14:18
Thanks for you great work, look forward for your training hyper parameters releasing.

**Comment by fabvio** [comment] 2019-07-28 14:33
Sorry for the delay, I am currently out of office for holidays so it's a little bit difficult to release the training code.

About the code, it's messy and should be reorganized in order to be fully usable, but I plan to do that in the near future. Meanwhile, I will first release my implementation of Hsu clustering loss. With that it should be easy to reproduce at least the first part of the paper. Stay tuned.

**Comment by anand-kummari** [comment] 2019-08-20 08:33
what is the loss function you have used to train the model. Can you release the loss function or give insights on how to implement it?

**Comment by fabvio** [comment] 2019-08-28 12:35
I released the loss function in the latest commit.

**Comment by noobliang** [comment] 2019-08-29 09:10
Hi， can you release the training code  ,thanks

**Comment by nieyan** [comment] 2019-08-30 08:08
Hi,  which version of pytorch do you use ?

**Comment by fabvio** [comment] 2019-08-30 08:23
I'm ordering the code but only in my free time so release will take a little longer, also I will probably write a journal extended version of the paper so I will explain better the procedures having broader page limitations.

About the pytorch version, the code has been deployed on pytorch <= 0.4.0, but it should work also on >= 0.4.0.

**Comment by kmsgnnew** [comment] 2019-12-20 10:58
@fabvio its great !!! will the code be available soon?

**Comment by nikhilbv** [comment] 2020-01-03 10:22
+1

**Comment by rashmi0888** [comment] 2020-02-18 16:05
Hi @fabvio . Can you release pretrained weights for descriptor size = 256 or 128?

**Comment by nikhilbv** [comment] 2020-05-05 13:17
Hi @fabvio, I Would love to know when the training code will be released?

**Comment by sandeepnmenon** [comment] 2021-02-25 10:06
+1
Would love to know when the training code will be released?

**Comment by ds12a** [comment] 2021-08-05 14:42
@fabvio Any updates on when the training code will be released?

**Comment by fabvio** [comment] 2021-08-05 16:14
Unfortunately, we stopped the development due to more urgent work. Anyways, I'd be happy to guide whoever wants to reimplement the method from scratch. Also, given that it could be adapted to any instance-based lane detector, it could also be plugged in to more recent baselines. You can contact me in private.

**Closed as completed by fabvio** 2021-08-05 16:14 UTC
